# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textDetectionGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.mainFrame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rightFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightFrame.sizePolicy().hasHeightForWidth())
        self.rightFrame.setSizePolicy(sizePolicy)
        self.rightFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.rightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.rightFrame)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(self.rightFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame_4 = QtWidgets.QFrame(self.page)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ori_image_L = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.ori_image_L.sizePolicy().hasHeightForWidth())
        self.ori_image_L.setSizePolicy(sizePolicy)
        self.ori_image_L.setText("")
        self.ori_image_L.setAlignment(QtCore.Qt.AlignCenter)
        self.ori_image_L.setObjectName("ori_image_L")
        self.gridLayout_8.addWidget(self.ori_image_L, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_9, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(142, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_8, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.detected_image_L = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.detected_image_L.sizePolicy().hasHeightForWidth())
        self.detected_image_L.setSizePolicy(sizePolicy)
        self.detected_image_L.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detected_image_L.setText("")
        self.detected_image_L.setAlignment(QtCore.Qt.AlignCenter)
        self.detected_image_L.setIndent(5)
        self.detected_image_L.setObjectName("detected_image_L")
        self.gridLayout_4.addWidget(self.detected_image_L, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_7, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(147, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 0, 1, 1)
        self.detectText_L = QtWidgets.QLabel(self.frame_6)
        self.detectText_L.setObjectName("detectText_L")
        self.gridLayout_7.addWidget(self.detectText_L, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_10.addWidget(self.frame_6, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frame_5, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_13.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem4 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem4, 0, 0, 1, 1)
        self.turnOn_PB = QtWidgets.QPushButton(self.frame_2)
        self.turnOn_PB.setObjectName("turnOn_PB")
        self.gridLayout_15.addWidget(self.turnOn_PB, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(216, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout_14.addWidget(self.frame_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_12.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.rightFrame, 0, 1, 1, 1)
        self.leftFrame = QtWidgets.QFrame(self.mainFrame)
        self.leftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftFrame.setObjectName("leftFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.leftFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 1, 0, 1, 1)
        self.dyDetect_PB = QtWidgets.QPushButton(self.leftFrame)
        self.dyDetect_PB.setObjectName("dyDetect_PB")
        self.gridLayout_3.addWidget(self.dyDetect_PB, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 440, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 3, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.leftFrame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.imagePath_LE = QtWidgets.QLineEdit(self.leftFrame)
        self.imagePath_LE.setEnabled(False)
        self.imagePath_LE.setObjectName("imagePath_LE")
        self.gridLayout_2.addWidget(self.imagePath_LE, 0, 1, 1, 2)
        self.toolButton = QtWidgets.QToolButton(self.leftFrame)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.leftFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.width_SB = QtWidgets.QSpinBox(self.leftFrame)
        self.width_SB.setMaximum(5000)
        self.width_SB.setProperty("value", 320)
        self.width_SB.setDisplayIntegerBase(10)
        self.width_SB.setObjectName("width_SB")
        self.gridLayout_2.addWidget(self.width_SB, 1, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.leftFrame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.height_SB = QtWidgets.QSpinBox(self.leftFrame)
        self.height_SB.setMaximum(5000)
        self.height_SB.setProperty("value", 320)
        self.height_SB.setObjectName("height_SB")
        self.gridLayout_2.addWidget(self.height_SB, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.leftFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.padding_DSB = QtWidgets.QDoubleSpinBox(self.leftFrame)
        self.padding_DSB.setMaximum(1.0)
        self.padding_DSB.setObjectName("padding_DSB")
        self.gridLayout_2.addWidget(self.padding_DSB, 3, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.leftFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 2)
        self.mincfd_DSB = QtWidgets.QDoubleSpinBox(self.leftFrame)
        self.mincfd_DSB.setMaximum(1.0)
        self.mincfd_DSB.setProperty("value", 0.5)
        self.mincfd_DSB.setObjectName("mincfd_DSB")
        self.gridLayout_2.addWidget(self.mincfd_DSB, 4, 2, 1, 1)
        self.detection_PB = QtWidgets.QPushButton(self.leftFrame)
        self.detection_PB.setObjectName("detection_PB")
        self.gridLayout_2.addWidget(self.detection_PB, 5, 0, 1, 3)
        self.recognition_PB = QtWidgets.QPushButton(self.leftFrame)
        self.recognition_PB.setEnabled(True)
        self.recognition_PB.setStyleSheet("")
        self.recognition_PB.setAutoDefault(False)
        self.recognition_PB.setDefault(False)
        self.recognition_PB.setObjectName("recognition_PB")
        self.gridLayout_2.addWidget(self.recognition_PB, 6, 0, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.leftFrame, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Detection GUI Tool"))
        self.label_3.setText(_translate("MainWindow", "Original Image"))
        self.detectText_L.setText(_translate("MainWindow", "Detected Image"))
        self.turnOn_PB.setText(_translate("MainWindow", "Turn on camera"))
        self.dyDetect_PB.setText(_translate("MainWindow", "Dynamic detect"))
        self.label.setText(_translate("MainWindow", "Image: "))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Width: "))
        self.label_5.setText(_translate("MainWindow", "Height: "))
        self.label_2.setText(_translate("MainWindow", "Padding: "))
        self.label_6.setText(_translate("MainWindow", "Min-confidence:"))
        self.detection_PB.setText(_translate("MainWindow", "Text Detection"))
        self.recognition_PB.setText(_translate("MainWindow", "Text Recognition"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

